version: "3"

services:
    app:
        build: .
        container_name: test-junior
        ports:
            - 3000:3000
        volumes:
            - ./src/:/usr/app/src
            - ./__tests__/:/usr/app/__tests__
        depends_on:
            - mongo
            - mongo-test
        environment:
            - DB_URL=mongodb://mongo:27017/dev

    mongo:
        image: mongo
        container_name: test-junior-mongo
        ports:
            - 27017:27017
        volumes:
            - data:/data/db
        environment:
            - MONGO_INITDB_DATABASE=dev

    mongo-test:
        image: mongo
        container_name: test-junior-mongo-test
        ports:
            - 27018:27017
        volumes:
            - data-test:/data/db

volumes:
    data:
    data-test:
