version: "3"

services:
    mongo:
        image: mongo
        container_name: test-junior-mongo
        ports:
            - 27017:27017
        volumes:
            - data:/data/db
        environment:
            - MONGO_INITDB_DATABASE=dev

volumes:
    data:
